### ISSUE TITLE
Connect_the_dots library?

### ISSUE THREAD

**Issue by boxuancui** [leonawicz/DataVisExamples#1]
Hi I really like your charts in "Connect_the_dots". What visualization library did you use? Do you mind sharing some code too? Thanks!

**Comment by leonawicz** [comment]
Thanks. These specific static graphics are made with ggplot2. What matters is having the right data and setting it up properly before plotting. It's nothing more than a plot of a bunch of lines weighted by attributes of the data set (such as population or distance, etc.).

You can probably use a couple functions in the [mapmate](https://github.com/leonawicz/mapmate ) package (also see [here](https://leonawicz.github.io/mapmate/)) to prep data for plotting, but afterward you will need to write your own plot code. You can investigate the plot code inside `save_map` for ideas on what you can do with your data, but this package will not likely plot exactly what you want.

In `mapmate`, see the help documentation for `gc_endpoints` and `gc_arcs`, specifically the example code at the bottom. You will see that the sequence of calls using the example `network` data set that comes with the package involves these two functions. Their purpose is to assist in turning a data frame that has the same structure of the `network` data set into a table containing great circle data.

This package is not aimed at doing exactly what you want, but you can lean on these two functions if you set your data up similarly and then decide how you want to plot the resulting table. The reason I say you will still want to write your own plot code is because `mapmate` is aimed at animations, and only specific types. The static graphics you are referencing look the way they do because different lines have their color and transparency levels weighted based on properties of the data. These plots are much older than `mapmate` and did not involve any special packages beyond using ggplot2 directly. I don't have code for this available but really all it involves is having different weights assigned to your lines and using those to affect how they are drawn.

It's just one of those things you have to experiment with and tweak your weights and colors and such to get the plot looking the way you want. The data prep functions from `mapmate` should get you most of the way there, allowing you to split great circles at the dateline and whatnot, leaving you with a data frame that will allow proper line segments to be plotted. How you style the plot is up to you. Hope that helps. 

Regards,
Matt
